### PR TITLE
Update `PAM50_cord.nii.gz` spinal cord segmentation

### LINKED ISSUE #17: `PAM50_cord.nii.gz` unecessarily encoded as FLOAT32
`PAM50_cord.nii.gz` is the spinal cord segmentation, and it is a binary mask (only 0 and 1), however it is encoded as FLOAT32:

```
julien-macbook:~/code/PAM50 $ fslhd template/PAM50_cord.nii.gz
filename	template/PAM50_cord.nii.gz

sizeof_hdr	348
data_type	FLOAT32
dim0		3
dim1		141
dim2		141
dim3		991
```

Given that FLOAT32 takes unecessary space, I suggest encoding this file as UINT8.

### LINKED ISSUE #19: The spinal cord in `PAM50_cord.nii.gz` is missing the caudal part
While working on #16, I noticed that the spinal cord segmentation does not cover the full part of the sacral cord. It stops at z-slice 79, while it should go down to ~50:

image

Note that updating `PAM50_cord.nii.gz` will also require updating the following files:
- `PAM50_levels.nii.gz`
- `PAM50_wm.nii.gz`
- `PAM50_gm.nii.gz`

### LINKED ISSUE #20: Extend C1 vertebrae on the `PAM50_levels` template file
Context: https://forum.spinalcordmri.org/t/c1-vertebral-level-labelling/1002/3

> Ah! OK, another reason for C1 to be cropped if the cord segmentation spans it entirely would be because it is difficult to find the top part of C1, hence the algorithm was trained to stop after a given distance that is based on the length of C1 in the PAM50 template (which is cropped):
>
> Historically, no user was interested in looking at C1, hence it was somewhat “neglected”, but I agree we should extend the segmentation on the PAM50 template so that the vertebral labeling would be more correct regarding C1 level.

### PR DESCRIPTION
**Pull request by jcohenadad**
This PR introduces an updated version of the `PAM50_cord.nii.gz` spinal cord segmentation and other related template files. This PR is required for https://github.com/spinalcordtoolbox/PAM50/pull/18.

Fixes #17, Fixes #19, Fixes #20

Scripts were created to do the modifications. I am uploading them on this repository as they might be useful in the future.

## Modification of `PAM50_cord.nii.gz`

The cord segmentation was only modified on the right side (faster, less error-prone), and then R-L symmetrization was ran:
````
python symmetrize_cord_segmentation.py
````

## Modification of `PAM50_levels.nii.gz`

After modifying the cord segmentation, the labeled segmentation had to be udpated:
````
python label_segmentation.py
````

Results (old vs. new):

anim

## Modification of `PAM50_wm.nii.gz` and `PAM50_gm.nii.gz`

Will be done in a subsequent PR: https://github.com/spinalcordtoolbox/PAM50/issues/23

### CODE REVIEW

**Comment by joshuacwnewton** [comment]
A couple of points I notice:

- The PR description mentions modifying wm/gm as a follow-up. But, do we also need to update `PAM50_levels_continuous.nii.gz`, `PAM50_csf.nii.gz`, and `PAM50_centerline.nii.gz`? I notice that these files are also missing some of the new slices that were added to the level file.
- There are some discrepancies between the old cord/levels files and the new cord/levels files. For example, at level `11`, the old level file (white) has some extra voxels compared to the new level file (green):

   oldvsnewlevels

   Another example is the boundary between the levels `19` and `20`:

   ezgif com-gif-maker

   Given that the changes in this PR are mainly focused on the C1/caudal areas, are these changes expected?

- How did you determine where to stop with the caudal segmentation? To my (very untrained) eyes, with the PAM50_t2.nii.gz as a background image, it seems like there may be more cord below where the segmentation stops. (I presume I'm naively missing something here, though?)

   ezgif com-gif-maker(1)

- I notice that the cord file still extends above where the new C1 level stops. Is this small region something we want to include in the levels file? Or is it excluded intentionally, since it's above the C1 level?

   cord_above_c1

**Comment by jcohenadad** [comment]
> The PR description mentions modifying wm/gm as a follow-up. But, do we also need to update PAM50_levels_continuous.nii.gz, PAM50_csf.nii.gz, and PAM50_centerline.nii.gz? I notice that these files are also missing some of the new slices that were added to the level file.

Excellent point-- see #25

**Comment by jcohenadad** [comment]
> There are some discrepancies between the old cord/levels files and the new cord/levels files. For example, at level 11, the old level file (white) has some extra voxels compared to the new level file (green):

That's fine-- the old was not perfectly symmetrized (I guess), so that was an issue (now fixed)

**Comment by jcohenadad** [comment]
> Another example is the boundary between the levels 19 and 20:

that's ok

**Comment by jcohenadad** [comment]
> Given that the changes in this PR are mainly focused on the C1/caudal areas, are these changes expected?

not expected, but better to improve where things could be improved

**Comment by jcohenadad** [comment]
> How did you determine where to stop with the caudal segmentation? To my (very untrained) eyes, with the PAM50_t2.nii.gz as a background image, it seems like there may be more cord below where the segmentation stops. (I presume I'm naively missing something here, though?)

Great question-- thank you for asking. When looking at the T1w, we notice that the cord is stopping at around L1/L2 disc. See this screen recording, with slices going caudally. When reaching L1/L2 disc, we notice that the spinal cord is becoming _very_ small, and the only tissue remaining are the nerve projecting on/from the sacral part of the spinal cord. Given that these nerves have a relatively short T2, when packed together, they appear as a 'dark mass' on T2w contrast, so it seems like cord tissue is still present below L1/L2, while in fact these are only nerves. 

https://github.com/spinalcordtoolbox/PAM50/assets/2482071/f1ad93a8-c2b0-41c3-a8e4-b30d993e971e

This is also suggested by the Frostell et al., where the cord is said to stop at around L1/L2. Although this needs to be taken with a grain of salt, given that we know there is inter-subject variability (notably wrt. size, age, etc.).

**Comment by jcohenadad** [comment]
[that](https://github.com/spinalcordtoolbox/PAM50/pull/21#issuecomment-1731738815) being said, from your screenshot, I notice that the cord seems undersegmented in the AP direction. Looking at the T1w image further confirms this. So I will likely add more cord tissue in the AP direction.

image

**Pull request merged**
